# Generated by Django 5.2.17 on 2026-09-02 00:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calibrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                ("lote", models.CharField(max_length=60, verbose_name="lote")),
                ("validade", models.DateField(verbose_name="validade")),
            ],
            options={
                "verbose_name": "calibrador",
                "verbose_name_plural": "calibradores",
                "ordering": ["nome", "-validade"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Controle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                ("lote", models.CharField(max_length=60, verbose_name="lote")),
                ("validade", models.DateField(verbose_name="validade")),
                (
                    "nivel",
                    models.PositiveSmallIntegerField(
                        help_text="1, 2, 3… conforme a concentração do material",
                        verbose_name="nível",
                    ),
                ),
                (
                    "valor_alvo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor declarado pelo fabricante, quando houver.",
                        max_digits=14,
                        null=True,
                        verbose_name="valor alvo",
                    ),
                ),
            ],
            options={
                "verbose_name": "material de controle",
                "verbose_name_plural": "materiais de controle",
                "ordering": ["nivel", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EspecificacaoQualidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex.: FT4 — ControlLab 2026",
                        max_length=150,
                        verbose_name="identificação",
                    ),
                ),
                (
                    "erro_total_maximo_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="erro total máximo (%)",
                    ),
                ),
                (
                    "erro_total_referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: Limite de aceitabilidade do provedor de ensaio de proficiência ControlLab",
                        max_length=300,
                        verbose_name="referência do erro total",
                    ),
                ),
                (
                    "erro_total_limiar_absoluto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="aplicar limite absoluto para resultados ≤",
                    ),
                ),
                (
                    "erro_total_maximo_absoluto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="erro total máximo absoluto (±)",
                    ),
                ),
                (
                    "erro_total_referencia_absoluto",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="referência do erro total absoluto",
                    ),
                ),
                (
                    "bias_maximo_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="bias máximo (%)",
                    ),
                ),
                (
                    "bias_referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: 50% do limite de aceitabilidade do provedor ControlLab",
                        max_length=300,
                        verbose_name="referência do bias",
                    ),
                ),
                (
                    "bias_limiar_absoluto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="aplicar limite absoluto para resultados ≤",
                    ),
                ),
                (
                    "bias_maximo_absoluto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="bias máximo absoluto (±)",
                    ),
                ),
                (
                    "bias_referencia_absoluto",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="referência do bias absoluto",
                    ),
                ),
                (
                    "nivel_significancia",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.05,
                        max_digits=4,
                        verbose_name="nível de significância (α)",
                    ),
                ),
                (
                    "vigente_desde",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="vigente desde",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
            ],
            options={
                "verbose_name": "especificação da qualidade analítica",
                "verbose_name_plural": "especificações da qualidade analítica",
                "ordering": ["mensurando", "-vigente_desde"],
            },
        ),
        migrations.CreateModel(
            name="LimiteImprecisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.PositiveSmallIntegerField(verbose_name="nível")),
                (
                    "maximo_pct",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="imprecisão máxima (%)",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        help_text="Ex.: 1/3 do limite de aceitabilidade do provedor ControlLab",
                        max_length=300,
                        verbose_name="referência científica",
                    ),
                ),
            ],
            options={
                "verbose_name": "limite de imprecisão",
                "verbose_name_plural": "limites de imprecisão",
                "ordering": ["nivel"],
            },
        ),
        migrations.CreateModel(
            name="Mensurando",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex.: FT4, Glicose, TSH",
                        max_length=100,
                        verbose_name="nome",
                    ),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        help_text="Ex.: ng/dL, mg/dL",
                        max_length=30,
                        verbose_name="unidade de medida",
                    ),
                ),
                (
                    "material_biologico",
                    models.CharField(
                        help_text="Ex.: soro, plasma, sangue total",
                        max_length=60,
                        verbose_name="material biológico",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensurando",
                "verbose_name_plural": "mensurandos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Reagente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                ("lote", models.CharField(max_length=60, verbose_name="lote")),
                ("validade", models.DateField(verbose_name="validade")),
            ],
            options={
                "verbose_name": "reagente",
                "verbose_name_plural": "reagentes",
                "ordering": ["nome", "-validade"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SistemaAnalitico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            (
                                "teste",
                                "Sistema Analítico em Teste (S.A.t) — método novo",
                            ),
                            (
                                "comparacao",
                                "Sistema Analítico de Comparação (S.A.c) — método em uso",
                            ),
                        ],
                        max_length=12,
                        verbose_name="papel no estudo",
                    ),
                ),
                (
                    "equipamento",
                    models.CharField(
                        help_text="Ex.: Atellica",
                        max_length=120,
                        verbose_name="equipamento",
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        help_text="Ex.: IH00715",
                        max_length=60,
                        verbose_name="número de série",
                    ),
                ),
                (
                    "metodologia",
                    models.CharField(
                        help_text="Ex.: Quimioluminescência",
                        max_length=120,
                        verbose_name="metodologia",
                    ),
                ),
                (
                    "intervalo_analitico_minimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="intervalo analítico — mínimo",
                    ),
                ),
                (
                    "intervalo_analitico_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="intervalo analítico — máximo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "sistema analítico",
                "verbose_name_plural": "sistemas analíticos",
                "ordering": ["equipamento", "numero_serie"],
            },
        ),
    ]
