# Generated by Django 5.2.17 on 2026-09-02 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="especificacaoqualidade",
            name="laboratorio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="especificacoes",
                to="contas.laboratorio",
                verbose_name="laboratório",
            ),
        ),
        migrations.AddField(
            model_name="limiteimprecisao",
            name="especificacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="limites_imprecisao",
                to="catalogo.especificacaoqualidade",
                verbose_name="especificação",
            ),
        ),
        migrations.AddField(
            model_name="mensurando",
            name="laboratorio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensurandos",
                to="contas.laboratorio",
                verbose_name="laboratório",
            ),
        ),
        migrations.AddField(
            model_name="especificacaoqualidade",
            name="mensurando",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="especificacoes",
                to="catalogo.mensurando",
                verbose_name="mensurando",
            ),
        ),
        migrations.AddField(
            model_name="sistemaanalitico",
            name="laboratorio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sistemas",
                to="contas.laboratorio",
                verbose_name="laboratório",
            ),
        ),
        migrations.AddField(
            model_name="reagente",
            name="sistema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reagentes",
                to="catalogo.sistemaanalitico",
                verbose_name="sistema analítico",
            ),
        ),
        migrations.AddField(
            model_name="controle",
            name="sistema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controles",
                to="catalogo.sistemaanalitico",
                verbose_name="sistema analítico",
            ),
        ),
        migrations.AddField(
            model_name="calibrador",
            name="sistema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calibradores",
                to="catalogo.sistemaanalitico",
                verbose_name="sistema analítico",
            ),
        ),
        migrations.AddConstraint(
            model_name="limiteimprecisao",
            constraint=models.UniqueConstraint(
                fields=("especificacao", "nivel"),
                name="limite_imprecisao_unico_por_nivel",
            ),
        ),
        migrations.AddConstraint(
            model_name="mensurando",
            constraint=models.UniqueConstraint(
                fields=("laboratorio", "nome", "material_biologico"),
                name="mensurando_unico_por_laboratorio",
            ),
        ),
    ]
