# Generated by Django 5.2.17 on 2026-09-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensurando",
            name="referencia_inferior",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Necessário para calcular a concordância clínica entre os métodos.",
                max_digits=14,
                null=True,
                verbose_name="intervalo de referência — limite inferior",
            ),
        ),
        migrations.AddField(
            model_name="mensurando",
            name="referencia_superior",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="intervalo de referência — limite superior",
            ),
        ),
    ]
