# Generated by Django 5.2.17 on 2026-09-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_mensurando_referencia_inferior_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="especificacaoqualidade",
            name="bias_derivado",
            field=models.BooleanField(
                default=True,
                help_text="Metade do erro total. Desligue para digitar um valor próprio.",
                verbose_name="bias derivado do erro total",
            ),
        ),
        migrations.AddField(
            model_name="especificacaoqualidade",
            name="fonte",
            field=models.CharField(
                choices=[
                    ("proficiencia", "Ensaio de proficiência"),
                    ("variacao_biologica", "Variação biológica"),
                    ("estado_da_arte", "Estado da arte"),
                    ("manual", "Manual — valores e justificativas digitados"),
                ],
                default="manual",
                help_text="Escolher uma fonte preenche as justificativas a partir do erro total.",
                max_length=25,
                verbose_name="fonte da especificação",
            ),
        ),
        migrations.AddField(
            model_name="especificacaoqualidade",
            name="fonte_descricao",
            field=models.CharField(
                blank=True,
                help_text="Ex.: provedor de ensaio de proficiência ControlLab",
                max_length=150,
                verbose_name="quem é a fonte",
            ),
        ),
        migrations.AddField(
            model_name="especificacaoqualidade",
            name="imprecisao_derivada",
            field=models.BooleanField(
                default=True,
                help_text="Um terço do erro total, aplicado a todos os níveis.",
                verbose_name="imprecisão derivada do erro total",
            ),
        ),
    ]
