# Generated by Django 5.2.17 on 2026-09-04 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0004_especificacaoqualidade_bias_derivado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controle",
            name="mensurando",
            field=models.ForeignKey(
                blank=True,
                help_text="Analito a que se refere o valor alvo deste frasco.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="controles",
                to="catalogo.mensurando",
                verbose_name="mensurando",
            ),
        ),
    ]
