# Generated by Django 5.2.17 on 2026-09-09 01:20

import django.db.models.deletion
from django.db import migrations, models


def herdar_do_equipamento(apps, schema_editor):
    """Copia o intervalo que estava no equipamento para os reagentes dele.

    Sem este passo a migração apagaria a faixa antes de o reagente existir para
    recebê-la. O valor herdado é uma aproximação — no equipamento ele valia para
    todos os analitos ao mesmo tempo, o que nunca foi verdade — mas jogar fora o
    que o laboratório já digitou seria pior do que herdar e deixar corrigir.
    """
    Reagente = apps.get_model("catalogo", "Reagente")
    for reagente in Reagente.objects.select_related("sistema").all():
        sistema = reagente.sistema
        if sistema.intervalo_analitico_minimo is None:
            continue
        reagente.intervalo_analitico_minimo = sistema.intervalo_analitico_minimo
        reagente.intervalo_analitico_maximo = sistema.intervalo_analitico_maximo
        reagente.save(
            update_fields=["intervalo_analitico_minimo", "intervalo_analitico_maximo"]
        )


def devolver_ao_equipamento(apps, schema_editor):
    """Volta atrás pegando a faixa do primeiro reagente de cada sistema."""
    SistemaAnalitico = apps.get_model("catalogo", "SistemaAnalitico")
    for sistema in SistemaAnalitico.objects.all():
        reagente = sistema.reagentes.exclude(intervalo_analitico_minimo=None).first()
        if reagente is None:
            continue
        sistema.intervalo_analitico_minimo = reagente.intervalo_analitico_minimo
        sistema.intervalo_analitico_maximo = reagente.intervalo_analitico_maximo
        sistema.save(
            update_fields=["intervalo_analitico_minimo", "intervalo_analitico_maximo"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0005_controle_mensurando"),
    ]

    operations = [
        migrations.AddField(
            model_name="reagente",
            name="intervalo_analitico_maximo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="intervalo analítico — máximo",
            ),
        ),
        migrations.AddField(
            model_name="reagente",
            name="intervalo_analitico_minimo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Menor valor que o ensaio mede, conforme a bula do lote.",
                max_digits=14,
                null=True,
                verbose_name="intervalo analítico — mínimo",
            ),
        ),
        migrations.AddField(
            model_name="reagente",
            name="mensurando",
            field=models.ForeignKey(
                blank=True,
                help_text="Analito que este kit mede. É o que dá sentido ao intervalo analítico.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reagentes",
                to="catalogo.mensurando",
                verbose_name="mensurando",
            ),
        ),
        migrations.RunPython(herdar_do_equipamento, devolver_ao_equipamento),
        migrations.RemoveField(
            model_name="sistemaanalitico",
            name="intervalo_analitico_maximo",
        ),
        migrations.RemoveField(
            model_name="sistemaanalitico",
            name="intervalo_analitico_minimo",
        ),
    ]
