# Generated by Django 5.2.17 on 2026-09-02 00:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=200, verbose_name="razão social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nome fantasia"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="cidade"),
                ),
                ("uf", models.CharField(blank=True, max_length=2, verbose_name="UF")),
                (
                    "responsavel_tecnico",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="responsável técnico"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
            ],
            options={
                "verbose_name": "laboratório",
                "verbose_name_plural": "laboratórios",
                "ordering": ["razao_social"],
            },
        ),
        migrations.CreateModel(
            name="Assinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("precisao", "Precisão — réplicas de material de controle"),
                            (
                                "comparabilidade",
                                "Comparabilidade — método antigo contra método novo",
                            ),
                            (
                                "completo",
                                "Precisão + Comparabilidade — inclui Erro Total e Sigma",
                            ),
                        ],
                        max_length=20,
                        verbose_name="módulo",
                    ),
                ),
                (
                    "inicio",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="início da vigência",
                    ),
                ),
                (
                    "fim",
                    models.DateField(
                        blank=True,
                        help_text="Vazio significa sem prazo de término.",
                        null=True,
                        verbose_name="fim da vigência",
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="observação"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "laboratorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="contas.laboratorio",
                        verbose_name="laboratório",
                    ),
                ),
            ],
            options={
                "verbose_name": "assinatura",
                "verbose_name_plural": "assinaturas",
                "ordering": ["laboratorio", "modulo"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        choices=[
                            ("analista", "Analista — insere dados e executa estudos"),
                            (
                                "responsavel",
                                "Responsável técnico — assina e libera relatórios",
                            ),
                            ("gestor", "Gestor — administra usuários do laboratório"),
                        ],
                        default="analista",
                        max_length=20,
                        verbose_name="função",
                    ),
                ),
                (
                    "conselho_profissional",
                    models.CharField(
                        blank=True,
                        help_text="CRF, CRM, CRBM — aparece na assinatura do relatório.",
                        max_length=50,
                        verbose_name="registro no conselho",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "laboratorio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vazio apenas para a equipe interna da plataforma.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="contas.laboratorio",
                        verbose_name="laboratório",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "momento",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="momento"
                    ),
                ),
                ("acao", models.CharField(max_length=100, verbose_name="ação")),
                ("objeto", models.CharField(max_length=200, verbose_name="objeto")),
                (
                    "detalhe",
                    models.JSONField(blank=True, default=dict, verbose_name="detalhe"),
                ),
                (
                    "laboratorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditoria",
                        to="contas.laboratorio",
                        verbose_name="laboratório",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoria",
                "verbose_name_plural": "registros de auditoria",
                "ordering": ["-momento"],
            },
        ),
    ]
