# Generated by Django 5.2.17 on 2026-09-02 00:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        ("contas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificacao",
                    models.CharField(
                        help_text="Ex.: Validação FT4 — Atellica — 2026",
                        max_length=150,
                        verbose_name="identificação",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("quantitativo", "Quantitativo — resultado numérico"),
                            ("qualitativo", "Qualitativo — reagente / não reagente"),
                        ],
                        default="quantitativo",
                        max_length=15,
                        verbose_name="tipo de método",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("precisao", "Precisão — réplicas de material de controle"),
                            (
                                "comparabilidade",
                                "Comparabilidade — método antigo contra método novo",
                            ),
                            (
                                "completo",
                                "Precisão + Comparabilidade — inclui Erro Total e Sigma",
                            ),
                        ],
                        max_length=20,
                        verbose_name="módulo utilizado",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="data de início",
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de conclusão"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho — dados em digitação"),
                            ("concluido", "Concluído — cálculo executado"),
                            (
                                "liberado",
                                "Liberado — assinado pelo responsável técnico",
                            ),
                            ("cancelado", "Cancelado"),
                        ],
                        default="rascunho",
                        max_length=12,
                        verbose_name="situação",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "especificacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudos",
                        to="catalogo.especificacaoqualidade",
                        verbose_name="especificação da qualidade",
                    ),
                ),
                (
                    "laboratorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudos",
                        to="contas.laboratorio",
                        verbose_name="laboratório",
                    ),
                ),
                (
                    "mensurando",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudos",
                        to="catalogo.mensurando",
                        verbose_name="mensurando",
                    ),
                ),
                (
                    "sistema_comparacao",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obrigatório quando o módulo inclui comparabilidade.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudos_como_comparacao",
                        to="catalogo.sistemaanalitico",
                        verbose_name="sistema de comparação (S.A.c)",
                    ),
                ),
                (
                    "sistema_teste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudos_como_teste",
                        to="catalogo.sistemaanalitico",
                        verbose_name="sistema em teste (S.A.t)",
                    ),
                ),
            ],
            options={
                "verbose_name": "estudo de validação",
                "verbose_name_plural": "estudos de validação",
                "ordering": ["-data_inicio", "identificacao"],
            },
        ),
        migrations.CreateModel(
            name="NivelEstudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        help_text="Corresponde ao nível do limite de imprecisão",
                        verbose_name="nível",
                    ),
                ),
                (
                    "concentracao_declarada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Usada para decidir entre o limite percentual e o absoluto.",
                        max_digits=14,
                        null=True,
                        verbose_name="concentração declarada",
                    ),
                ),
                (
                    "controle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="niveis_estudo",
                        to="catalogo.controle",
                        verbose_name="material de controle",
                    ),
                ),
                (
                    "estudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveis",
                        to="estudos.estudo",
                        verbose_name="estudo",
                    ),
                ),
            ],
            options={
                "verbose_name": "nível do estudo",
                "verbose_name_plural": "níveis do estudo",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Replica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corrida",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="corrida / dia",
                    ),
                ),
                (
                    "sequencia",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="réplica na corrida",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="valor medido"
                    ),
                ),
                (
                    "excluida",
                    models.BooleanField(
                        default=False,
                        help_text="Exclusão exige justificativa registrada — a réplica não é apagada.",
                        verbose_name="excluída do cálculo",
                    ),
                ),
                (
                    "justificativa_exclusao",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="justificativa da exclusão",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replicas",
                        to="estudos.nivelestudo",
                        verbose_name="nível",
                    ),
                ),
            ],
            options={
                "verbose_name": "réplica",
                "verbose_name_plural": "réplicas",
                "ordering": ["corrida", "sequencia"],
            },
        ),
        migrations.CreateModel(
            name="Veredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            (
                                "APROVADO",
                                "Aprovado — dentro de todos os limites especificados",
                            ),
                            (
                                "REPROVADO",
                                "Reprovado — ao menos um indicador fora do limite",
                            ),
                            (
                                "INDETERMINADO",
                                "Indeterminado — dados insuficientes para decidir",
                            ),
                        ],
                        max_length=15,
                        verbose_name="resultado",
                    ),
                ),
                (
                    "detalhamento",
                    models.JSONField(
                        default=dict, verbose_name="detalhamento do cálculo"
                    ),
                ),
                (
                    "versao_motor",
                    models.CharField(
                        default="1.0.0",
                        max_length=20,
                        verbose_name="versão do motor de cálculo",
                    ),
                ),
                (
                    "calculado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="calculado em"
                    ),
                ),
                (
                    "liberado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="liberado em"
                    ),
                ),
                (
                    "estudo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veredito",
                        to="estudos.estudo",
                        verbose_name="estudo",
                    ),
                ),
                (
                    "liberado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vereditos_liberados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="liberado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "veredito",
                "verbose_name_plural": "vereditos",
                "ordering": ["-calculado_em"],
            },
        ),
        migrations.CreateModel(
            name="AmostraQualitativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificacao",
                    models.CharField(
                        max_length=60, verbose_name="identificação da amostra"
                    ),
                ),
                (
                    "resultado_referencia",
                    models.BooleanField(verbose_name="referência é reagente"),
                ),
                (
                    "resultado_teste",
                    models.BooleanField(verbose_name="método em teste é reagente"),
                ),
                (
                    "estudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amostras_qualitativas",
                        to="estudos.estudo",
                        verbose_name="estudo",
                    ),
                ),
            ],
            options={
                "verbose_name": "amostra qualitativa",
                "verbose_name_plural": "amostras qualitativas",
                "ordering": ["identificacao"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("estudo", "identificacao"),
                        name="amostra_qualitativa_unica_por_estudo",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AmostraComparacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificacao",
                    models.CharField(
                        max_length=60, verbose_name="identificação da amostra"
                    ),
                ),
                (
                    "valor_comparacao",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        verbose_name="resultado no sistema de comparação",
                    ),
                ),
                (
                    "valor_teste",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        verbose_name="resultado no sistema em teste",
                    ),
                ),
                (
                    "excluida",
                    models.BooleanField(
                        default=False, verbose_name="excluída do cálculo"
                    ),
                ),
                (
                    "justificativa_exclusao",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="justificativa da exclusão",
                    ),
                ),
                (
                    "estudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amostras_comparacao",
                        to="estudos.estudo",
                        verbose_name="estudo",
                    ),
                ),
            ],
            options={
                "verbose_name": "amostra de comparação",
                "verbose_name_plural": "amostras de comparação",
                "ordering": ["identificacao"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("estudo", "identificacao"),
                        name="amostra_comparacao_unica_por_estudo",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="nivelestudo",
            constraint=models.UniqueConstraint(
                fields=("estudo", "numero"), name="nivel_unico_por_estudo"
            ),
        ),
        migrations.AddConstraint(
            model_name="replica",
            constraint=models.UniqueConstraint(
                fields=("nivel", "corrida", "sequencia"),
                name="replica_unica_por_corrida",
            ),
        ),
    ]
