# Generated by Django 5.2.17 on 2026-09-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudo",
            name="desenho_precisao",
            field=models.CharField(
                choices=[
                    (
                        "multiplas_corridas",
                        "Múltiplas corridas — 5 dias consecutivos, 5 réplicas por dia",
                    ),
                    (
                        "corrida_unica",
                        "Corrida única — todas as réplicas no mesmo dia (mínimo 10)",
                    ),
                ],
                default="multiplas_corridas",
                help_text="Múltiplas corridas mede repetibilidade E precisão intermediária. Corrida única mede apenas repetibilidade, e o Erro Total calculado a partir dela subestima o erro da rotina.",
                max_length=25,
                verbose_name="desenho do estudo de precisão",
            ),
        ),
    ]
