# Generated by Django 5.2.17 on 2026-09-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0002_estudo_desenho_precisao"),
    ]

    operations = [
        migrations.AddField(
            model_name="nivelestudo",
            name="media_interlaboratorial",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Média do mesmo lote de controle no grupo de pares. É o alvo do bias. Em branco, a exatidão deste nível não é avaliada.",
                max_digits=14,
                null=True,
                verbose_name="média do estudo interlaboratorial",
            ),
        ),
        migrations.AddField(
            model_name="nivelestudo",
            name="provedor_interlaboratorial",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e-Lab", "e-Lab"),
                    ("Unity", "Unity (Bio-Rad)"),
                    ("fleet", "fleet do fabricante"),
                    ("outro", "outro programa interlaboratorial"),
                ],
                help_text="De onde veio a média informada — vai para o relatório.",
                max_length=20,
                verbose_name="programa interlaboratorial",
            ),
        ),
    ]
