# Generated by Django 5.2.17 on 2026-09-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0003_nivelestudo_media_interlaboratorial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudo",
            name="referencia_comparacao_inferior",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="referência do método de comparação — inferior",
            ),
        ),
        migrations.AddField(
            model_name="estudo",
            name="referencia_comparacao_superior",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="referência do método de comparação — superior",
            ),
        ),
        migrations.AddField(
            model_name="estudo",
            name="referencia_teste_inferior",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="referência do método em teste — inferior",
            ),
        ),
        migrations.AddField(
            model_name="estudo",
            name="referencia_teste_superior",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="referência do método em teste — superior",
            ),
        ),
    ]
