# Generated by Django 5.2.17 on 2026-09-09 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0004_estudo_referencia_comparacao_inferior_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="amostracomparacao",
            name="amostra_comparacao_unica_por_estudo",
        ),
    ]
