# Generated by Django 5.2.17 on 2026-09-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0005_amostra_aceita_codigo_repetido"),
    ]

    operations = [
        migrations.AddField(
            model_name="veredito",
            name="analise_atualizada_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="análise atualizada em"
            ),
        ),
        migrations.AddField(
            model_name="veredito",
            name="analise_critica",
            field=models.TextField(
                blank=True,
                help_text="Observações, nuances e explicações que acompanham o relatório.",
                verbose_name="conclusão / análise crítica",
            ),
        ),
    ]
