# Generated by Django 5.2.17 on 2026-09-09 03:13

"""O veredito passa a ser decidido por pessoa, não pelo cálculo.

Os retratos que já existem precisam de tratamento diferente conforme tenham ou
não passado pela assinatura de alguém:

* **Já liberado** — um responsável técnico assinou aquele resultado. A decisão
  existe; o que faltava era o campo para registrá-la. Ela é preservada, com a
  assinatura como autor e data.
* **Ainda não liberado** — o valor guardado é uma classificação automática que
  ninguém confirmou. Volta a ``PENDENTE``, para ser decidido na tela. Fabricar
  uma decisão retroativa seria pôr no documento o nome de quem não decidiu.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preservar_decisoes_assinadas(apps, schema_editor):
    Veredito = apps.get_model("estudos", "Veredito")

    assinados = Veredito.objects.exclude(liberado_em=None)
    for veredito in assinados.iterator():
        if veredito.resultado in {"APROVADO", "REPROVADO"}:
            veredito.decidido_por_id = veredito.liberado_por_id
            veredito.decidido_em = veredito.liberado_em
        else:
            veredito.resultado = "PENDENTE"
        veredito.save(update_fields=["resultado", "decidido_por", "decidido_em"])

    Veredito.objects.filter(liberado_em=None).update(
        resultado="PENDENTE", decidido_por=None, decidido_em=None
    )


def desfazer(apps, schema_editor):
    """A volta apaga só o registro de autoria — o resultado continua onde está."""
    Veredito = apps.get_model("estudos", "Veredito")
    Veredito.objects.update(decidido_por=None, decidido_em=None)



class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0006_veredito_recebe_a_analise_critica"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nivelestudo",
            name="concentracao_declarada",
        ),
        migrations.AddField(
            model_name="veredito",
            name="decidido_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="veredito decidido em"
            ),
        ),
        migrations.AddField(
            model_name="veredito",
            name="decidido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vereditos_decididos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="veredito decidido por",
            ),
        ),
        migrations.AlterField(
            model_name="nivelestudo",
            name="provedor_interlaboratorial",
            field=models.CharField(
                blank=True,
                help_text="Nome do programa de onde veio a média — vai para o relatório.",
                max_length=80,
                verbose_name="programa interlaboratorial",
            ),
        ),
        migrations.AlterField(
            model_name="veredito",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Aguardando a decisão do responsável"),
                    ("APROVADO", "Estudo aprovado"),
                    ("REPROVADO", "Estudo reprovado"),
                ],
                default="PENDENTE",
                help_text="Decidido por pessoa na tela do estudo, não pelo cálculo.",
                max_length=15,
                verbose_name="veredito do responsável",
            ),
        ),
        migrations.RunPython(preservar_decisoes_assinadas, desfazer),
    ]
