# Generated by Django 5.2.17 on 2026-09-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0007_veredito_decidido_por_pessoa"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="amostraqualitativa",
            name="amostra_qualitativa_unica_por_estudo",
        ),
    ]
