# Generated by Django 5.2.17 on 2026-09-10 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0008_amostra_qualitativa_aceita_codigo_repetido"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecorteRegressao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rotulo",
                    models.CharField(
                        help_text="Como este recorte aparece no relatório. Ex.: “Faixa baixa — até 150 mg/dL”.",
                        max_length=80,
                        verbose_name="rótulo",
                    ),
                ),
                (
                    "minimo",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Limite inferior da faixa, no sistema de comparação.",
                        max_digits=14,
                        verbose_name="concentração mínima",
                    ),
                ),
                (
                    "maximo",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Limite superior da faixa, no sistema de comparação.",
                        max_digits=14,
                        verbose_name="concentração máxima",
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        help_text="O motivo de examinar esta faixa em separado. Vai para o relatório junto do recorte — sem ele, um subconjunto escolhido à mão não se sustenta.",
                        verbose_name="por que esta faixa",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recortes_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "estudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recortes",
                        to="estudos.estudo",
                        verbose_name="estudo",
                    ),
                ),
            ],
            options={
                "verbose_name": "recorte da regressão",
                "verbose_name_plural": "recortes da regressão",
                "ordering": ["minimo", "pk"],
            },
        ),
    ]
